# Generated by Django 4.0 on 2024-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('amount_in_cents', models.IntegerField()),
                ('timestamp_utc', models.DateTimeField()),
                ('statement_reference', models.CharField(max_length=18)),
            ],
        ),
    ]
