version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5430:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8666
    volumes:
      - .:/app
    ports:
      - "8666:8666"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5430
    restart: always